# The container images used in this pipeline are built from this
# GitLab project: https://gitlab.gnome.org/sthursfield/tracker-oci-images/

stages:
  - test

test-autotools-fedora-latest:
  stage: test
  image: registry.gitlab.gnome.org/sthursfield/tracker-oci-images/amd64/fedora:latest

  script:
    # First build and install latest Tracker using Meson (the Autotools build
    # of Tracker is tested already in tracker.git, we don't need to suffer that
    # again).
    - mkdir /opt/tracker; chown tracker:tracker /opt/tracker
    - su tracker -c 'git clone https://gitlab.gnome.org/GNOME/tracker'
    - su tracker -c 'cd tracker; mkdir build'
    - su tracker -c 'cd tracker/build; meson .. --prefix=/opt/tracker -Ddbus_services=/opt/tracker/share/dbus-1/services -Dsystemd_user_services=/opt/tracker/lib/systemd/user'
    - su tracker -c 'cd tracker/build; ninja install'
    # Delete the build tree now that we're done with it, or `intltool-update`
    # raise a spurious error later during `make check`.
    - su tracker -c 'rm -Rf tracker'

    # Now build tracker-miners using Autotools, linking against new Tracker.
    - PKG_CONFIG_PATH=/opt/tracker/lib64/pkgconfig/ su tracker -c './autogen.sh --prefix=/opt/tracker'
    - su tracker -c 'make -j'
    - su tracker -c 'LD_LIBRARY_PATH=/opt/tracker/lib64 VERBOSE=1 make check'
    - su tracker -c 'LD_LIBRARY_PATH=/opt/tracker/lib64 make functional-test'

test-meson-fedora-latest:
  stage: test
  image: registry.gitlab.gnome.org/sthursfield/tracker-oci-images/amd64/fedora:latest

  script:
    # We can build and test tracker-miners against tracker just by building
    # tracker as a submodule.
    #
    # Note that this approach doesn't currently work for the functional-tests,
    # they require the ontologies and domain rules from tracker to be installed
    # somewhere. It would be nice to improve the functional-tests so that they
    # will run without depending on any files outside of the build tree. Note
    # that Tracker is installed on the host here, thanks to `dnf builddep`.
    - su tracker -c 'mkdir subprojects; cd subprojects; git clone https://gitlab.gnome.org/GNOME/tracker'
    - su tracker -c 'mkdir build'
    - su tracker -c 'cd build; meson .. --prefix=/usr'
    - su tracker -c 'cd build; ninja'
    - |
      # Remove the many "CI_" variables from the environment. Meson dumps the
      # whole environment for every failed test, and that gives a whole
      # screenful of junk each time unless we strip these.
      unset $(env|grep -o '^CI_[^=]*')

      su tracker -c 'cd build; meson test --suite tracker-miners --print-errorlogs'
