# The container images used in this pipeline are built from this
# GitLab project: https://gitlab.gnome.org/GNOME/tracker-oci-images

variables:
  # These can be used to see verbose log output from the functional-tests.
  # See HACKING.md for more information.
  TRACKER_VERBOSITY: "1"
  TRACKER_TESTS_VERBOSE: "no"

  # This can be used when debugging test failures that only occur within GitLab CI.
  MESON_TEST_EXTRA_ARGS: ""

stages:
  - website

pages:
  stage: website
  image: registry.gitlab.gnome.org/gnome/tracker-oci-images/amd64/fedora:latest
  before_script:
    - pip3 install mkdocs mkdocs-cinder
  script:
    # Build tracker and tracker-miners to generate the API documentation.
    - ls
    - su tracker -c '.gitlab-ci/checkout-tracker.sh'
    - su tracker -c 'mkdir build; cd build; meson .. --prefix=/tmp/tracker -Dtracker_core=subproject; ninja install'
    # Generate the website using mkdocs.
    - |
      tracker_commit=$(git -C ./subprojects/tracker rev-parse HEAD)
      ./docs/website/build.py --api-docs=/tmp/tracker/share/gtk-doc/html --tracker-commit=${tracker_commit}
  artifacts:
    paths:
      - public
  only:
    - master
    - sam/website
